apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - env:
        - name: ENV
          value: dev
        image: nginx:latest-dev
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-app-test
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: nginx-app-test-0.1.0
  name: my-app-nginx-app-test-test-connection
  namespace: dev
spec:
  containers:
  - args:
    - my-app-nginx-app-test:80
    command:
    - wget
    image: busybox
    name: wget
  restartPolicy: Never
