jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Application
        run: echo "Deployment steps..."

  cleanup:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Cleanup Runner
        run: |
          echo "Cleaning up workspace and Docker artifacts..."
          rm -rf ${{ github.workspace }}
          docker system prune -af --volumes
