name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      - prd
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: test-argo

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Render Helm Templates for the Environment
      - name: Render Helm Templates
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            helm template my-nginx-app ./helm --namespace dev > kustomize/base/rendered.yaml
          elif [[ "${{ github.ref_name }}" == "prd" ]]; then
            helm template my-nginx-app ./helm --namespace prd > kustomize/base/rendered.yaml
          fi

      # Step 3: Apply Kustomize Overlays
      - name: Apply Kustomize Overlays
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            kustomize build kustomize/overlays/dev | kubectl apply -f -
          elif [[ "${{ github.ref_name }}" == "prd" ]]; then
            kustomize build kustomize/overlays/prd | kubectl apply -f -
          fi

      # Step 4: Log in to Argo CD CLI
      - name: Log in to Argo CD CLI
        run: |
          argocd login 10.42.0.209:8080 --username admin --password 4GouUjDgTj --insecure
    

      # Step 5: Trigger ArgoCD Sync (Optional if Auto-Sync is Disabled)
      - name: Trigger ArgoCD Sync
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            argocd app sync nginx-app-dev
            argocd app wait nginx-app-dev --timeout 300
          elif [[ "${{ github.ref_name }}" == "prd" ]]; then
            argocd app sync nginx-app-prd
            argocd app wait nginx-app-prd --timeout 300
          fi

      # Step 6: Cleanup Workspace
      - name: Cleanup Workspace
        if: always()
        run: |
          echo "Cleaning up runner workspace..."
          rm -rf ${{ github.workspace }}

      # Step 7: Cleanup Docker Images (Optional)
      - name: Cleanup Docker
        if: always()
        run: |
          echo "Cleaning up Docker images and volumes..."
          docker system prune -af --volumes    
